version: '3.1'

services:
  web:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}-web
    working_dir: /application
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/application
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/log:/var/log/nginx
    depends_on:
      - php
    links:
      - php
  php:
    build: ./.docker/php
    container_name: ${COMPOSE_PROJECT_NAME}-php
    working_dir: /application
    volumes:
      - ./:/application
      - ./.docker/log:/var/log
      - ./.docker/php/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
    ports:
      - ${EXT_PORT_PHP}:9001
    links:
      - mysql
      - memcached
      - rabbitmq
  mysql:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    volumes:
      - ./.docker/mysql/config.cnf:/etc/mysql/conf.d/custom.cnf
      - ./.docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - ${EXT_PORT_MYSQL}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  memcached:
    image: memcached:alpine
    container_name: ${COMPOSE_PROJECT_NAME}-memcached
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name:  ${COMPOSE_PROJECT_NAME}-rabbitmq
    hostname: rabbitmq
    volumes:
      - ./.docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - ${EXT_PORT_RABBIRMQ_GUI}:15672
      - ${EXT_PORT_RABBIRMQ}:5672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIRMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIRMQ_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=/